/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.example;

public class App {

    public static void main(String[] args) {
        SayHelloClass sayHelloClass = new SayHelloClass();
        sayHelloClass.SayHello();
    }
}
